### ISSUE TITLE
Add html and ts linting in project repo configuration so all developers use same style

### ISSUE THREAD

**Issue by Michiel-s** [AmpersandTarski/prototype-frontend#32]

**Comment by Michiel-s** [comment]
I propose to use Prettier and use the following specification

`.prettierrc.yml`
```yml
# .prettierrc or .prettierrc.yaml
tabWidth: 2
trailingComma: all
printWidth: 120
useTabs: false
overrides:
  - files:
      - "*.html"
    options:
      tabWidth: 4
```
